// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MemoryInfo() {
  return window['go']['main']['App']['MemoryInfo']();
}

export function RealTimeMemoryInfo() {
  return window['go']['main']['App']['RealTimeMemoryInfo']();
}
